//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 10:10:51 PM CST 
//


package uia.d2d.in.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CsvType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CsvType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rowKey" type="{http://d2d.uia/in/xml}SqlColumnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="const" type="{http://d2d.uia/in/xml}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="plan" type="{http://d2d.uia/in/xml}PlanType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="firstRow" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="rowCount" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="columnCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CsvType", propOrder = {
    "rowKey",
    "_const",
    "plan"
})
public class CsvType {

    protected List<SqlColumnType> rowKey;
    @XmlElement(name = "const")
    protected List<ParameterType> _const;
    protected List<PlanType> plan;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "firstRow")
    protected Integer firstRow;
    @XmlAttribute(name = "rowCount")
    protected Integer rowCount;
    @XmlAttribute(name = "columnCount", required = true)
    protected int columnCount;

    /**
     * Gets the value of the rowKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rowKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRowKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SqlColumnType }
     * 
     * 
     */
    public List<SqlColumnType> getRowKey() {
        if (rowKey == null) {
            rowKey = new ArrayList<SqlColumnType>();
        }
        return this.rowKey;
    }

    /**
     * Gets the value of the const property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the const property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConst().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getConst() {
        if (_const == null) {
            _const = new ArrayList<ParameterType>();
        }
        return this._const;
    }

    /**
     * Gets the value of the plan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanType }
     * 
     * 
     */
    public List<PlanType> getPlan() {
        if (plan == null) {
            plan = new ArrayList<PlanType>();
        }
        return this.plan;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstRow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getFirstRow() {
        if (firstRow == null) {
            return  0;
        } else {
            return firstRow;
        }
    }

    /**
     * Sets the value of the firstRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFirstRow(Integer value) {
        this.firstRow = value;
    }

    /**
     * Gets the value of the rowCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRowCount() {
        if (rowCount == null) {
            return  0;
        } else {
            return rowCount;
        }
    }

    /**
     * Sets the value of the rowCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRowCount(Integer value) {
        this.rowCount = value;
    }

    /**
     * Gets the value of the columnCount property.
     * 
     */
    public int getColumnCount() {
        return columnCount;
    }

    /**
     * Sets the value of the columnCount property.
     * 
     */
    public void setColumnCount(int value) {
        this.columnCount = value;
    }

}
