//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 10:10:51 PM CST 
//


package uia.d2d.in.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="simpleJob" type="{http://d2d.uia/in/xml}SimpleJobType"/>
 *           &lt;element name="sheetJob" type="{http://d2d.uia/in/xml}SheetJobType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostType", propOrder = {
    "simpleJobOrSheetJob"
})
public class PostType {

    @XmlElements({
        @XmlElement(name = "simpleJob", type = SimpleJobType.class),
        @XmlElement(name = "sheetJob", type = SheetJobType.class)
    })
    protected List<JobType> simpleJobOrSheetJob;

    /**
     * Gets the value of the simpleJobOrSheetJob property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simpleJobOrSheetJob property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimpleJobOrSheetJob().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleJobType }
     * {@link SheetJobType }
     * 
     * 
     */
    public List<JobType> getSimpleJobOrSheetJob() {
        if (simpleJobOrSheetJob == null) {
            simpleJobOrSheetJob = new ArrayList<JobType>();
        }
        return this.simpleJobOrSheetJob;
    }

}
