//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.12 at 09:02:51 PM CST 
//


package uia.d2d.in.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="csvSpace" type="{http://d2d.uia/in/xml}CsvSpaceType"/>
 *         &lt;element name="scConvSpace" type="{http://d2d.uia/in/xml}SCConvSpaceType"/>
 *         &lt;element name="ccConvSpace" type="{http://d2d.uia/in/xml}CCConvSpaceType"/>
 *         &lt;element name="constSpace" type="{http://d2d.uia/in/xml}ConstSpaceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceType", propOrder = {
    "csvSpace",
    "scConvSpace",
    "ccConvSpace",
    "constSpace"
})
public class WorkspaceType {

    @XmlElement(required = true)
    protected CsvSpaceType csvSpace;
    @XmlElement(required = true)
    protected SCConvSpaceType scConvSpace;
    @XmlElement(required = true)
    protected CCConvSpaceType ccConvSpace;
    @XmlElement(required = true)
    protected ConstSpaceType constSpace;

    /**
     * Gets the value of the csvSpace property.
     * 
     * @return
     *     possible object is
     *     {@link CsvSpaceType }
     *     
     */
    public CsvSpaceType getCsvSpace() {
        return csvSpace;
    }

    /**
     * Sets the value of the csvSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsvSpaceType }
     *     
     */
    public void setCsvSpace(CsvSpaceType value) {
        this.csvSpace = value;
    }

    /**
     * Gets the value of the scConvSpace property.
     * 
     * @return
     *     possible object is
     *     {@link SCConvSpaceType }
     *     
     */
    public SCConvSpaceType getScConvSpace() {
        return scConvSpace;
    }

    /**
     * Sets the value of the scConvSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCConvSpaceType }
     *     
     */
    public void setScConvSpace(SCConvSpaceType value) {
        this.scConvSpace = value;
    }

    /**
     * Gets the value of the ccConvSpace property.
     * 
     * @return
     *     possible object is
     *     {@link CCConvSpaceType }
     *     
     */
    public CCConvSpaceType getCcConvSpace() {
        return ccConvSpace;
    }

    /**
     * Sets the value of the ccConvSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCConvSpaceType }
     *     
     */
    public void setCcConvSpace(CCConvSpaceType value) {
        this.ccConvSpace = value;
    }

    /**
     * Gets the value of the constSpace property.
     * 
     * @return
     *     possible object is
     *     {@link ConstSpaceType }
     *     
     */
    public ConstSpaceType getConstSpace() {
        return constSpace;
    }

    /**
     * Sets the value of the constSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstSpaceType }
     *     
     */
    public void setConstSpace(ConstSpaceType value) {
        this.constSpace = value;
    }

}
