//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 12:41:19 PM CST 
//


package uia.d2d.sheet.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://d2d.uia/sheet/xml}CellType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="property" type="{http://d2d.uia/sheet/xml}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="object" type="{http://d2d.uia/sheet/xml}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="list" type="{http://d2d.uia/sheet/xml}ListType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="custom" type="{http://d2d.uia/sheet/xml}CustomType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" default="rows" />
 *       &lt;attribute name="row" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="col" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListType", propOrder = {
    "propertyOrObjectOrList"
})
public class ListType
    extends CellType
{

    @XmlElements({
        @XmlElement(name = "property", type = PropertyType.class),
        @XmlElement(name = "object", type = ObjectType.class),
        @XmlElement(name = "list", type = ListType.class),
        @XmlElement(name = "custom", type = CustomType.class)
    })
    protected List<CellType> propertyOrObjectOrList;
    @XmlAttribute(name = "mode")
    protected String mode;
    @XmlAttribute(name = "row")
    protected Integer row;
    @XmlAttribute(name = "col")
    protected Integer col;

    /**
     * Gets the value of the propertyOrObjectOrList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyOrObjectOrList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyOrObjectOrList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * {@link ObjectType }
     * {@link ListType }
     * {@link CustomType }
     * 
     * 
     */
    public List<CellType> getPropertyOrObjectOrList() {
        if (propertyOrObjectOrList == null) {
            propertyOrObjectOrList = new ArrayList<CellType>();
        }
        return this.propertyOrObjectOrList;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        if (mode == null) {
            return "rows";
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRow() {
        if (row == null) {
            return  0;
        } else {
            return row;
        }
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRow(Integer value) {
        this.row = value;
    }

    /**
     * Gets the value of the col property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCol() {
        if (col == null) {
            return  0;
        } else {
            return col;
        }
    }

    /**
     * Sets the value of the col property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCol(Integer value) {
        this.col = value;
    }

}
