//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 12:41:19 PM CST 
//


package uia.d2d.sheet.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://d2d.uia/sheet/xml}CellType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="property" type="{http://d2d.uia/sheet/xml}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="object" type="{http://d2d.uia/sheet/xml}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="list" type="{http://d2d.uia/sheet/xml}ListType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="custom" type="{http://d2d.uia/sheet/xml}CustomType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectType", propOrder = {
    "propertyOrObjectOrList"
})
public class ObjectType
    extends CellType
{

    @XmlElements({
        @XmlElement(name = "property", type = PropertyType.class),
        @XmlElement(name = "object", type = ObjectType.class),
        @XmlElement(name = "list", type = ListType.class),
        @XmlElement(name = "custom", type = CustomType.class)
    })
    protected List<CellType> propertyOrObjectOrList;

    /**
     * Gets the value of the propertyOrObjectOrList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyOrObjectOrList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyOrObjectOrList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * {@link ObjectType }
     * {@link ListType }
     * {@link CustomType }
     * 
     * 
     */
    public List<CellType> getPropertyOrObjectOrList() {
        if (propertyOrObjectOrList == null) {
            propertyOrObjectOrList = new ArrayList<CellType>();
        }
        return this.propertyOrObjectOrList;
    }

}
