//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 12:41:19 PM CST 
//


package uia.d2d.sheet.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uia.d2d.sheet.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Workspace_QNAME = new QName("http://d2d.uia/sheet/xml", "workspace");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uia.d2d.sheet.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WorkspaceType }
     * 
     */
    public WorkspaceType createWorkspaceType() {
        return new WorkspaceType();
    }

    /**
     * Create an instance of {@link CustomType }
     * 
     */
    public CustomType createCustomType() {
        return new CustomType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link SheetSpaceType }
     * 
     */
    public SheetSpaceType createSheetSpaceType() {
        return new SheetSpaceType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link SheetType }
     * 
     */
    public SheetType createSheetType() {
        return new SheetType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link FormatterType }
     * 
     */
    public FormatterType createFormatterType() {
        return new FormatterType();
    }

    /**
     * Create an instance of {@link FormatterSpaceType }
     * 
     */
    public FormatterSpaceType createFormatterSpaceType() {
        return new FormatterSpaceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkspaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://d2d.uia/sheet/xml", name = "workspace")
    public JAXBElement<WorkspaceType> createWorkspace(WorkspaceType value) {
        return new JAXBElement<WorkspaceType>(_Workspace_QNAME, WorkspaceType.class, null, value);
    }

}
