//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.04 at 12:41:19 PM CST 
//


package uia.d2d.sheet.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sheetSpace" type="{http://d2d.uia/sheet/xml}SheetSpaceType"/>
 *         &lt;element name="formatterSpace" type="{http://d2d.uia/sheet/xml}FormatterSpaceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceType", propOrder = {
    "sheetSpace",
    "formatterSpace"
})
public class WorkspaceType {

    @XmlElement(required = true)
    protected SheetSpaceType sheetSpace;
    @XmlElement(required = true)
    protected FormatterSpaceType formatterSpace;

    /**
     * Gets the value of the sheetSpace property.
     * 
     * @return
     *     possible object is
     *     {@link SheetSpaceType }
     *     
     */
    public SheetSpaceType getSheetSpace() {
        return sheetSpace;
    }

    /**
     * Sets the value of the sheetSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link SheetSpaceType }
     *     
     */
    public void setSheetSpace(SheetSpaceType value) {
        this.sheetSpace = value;
    }

    /**
     * Gets the value of the formatterSpace property.
     * 
     * @return
     *     possible object is
     *     {@link FormatterSpaceType }
     *     
     */
    public FormatterSpaceType getFormatterSpace() {
        return formatterSpace;
    }

    /**
     * Sets the value of the formatterSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatterSpaceType }
     *     
     */
    public void setFormatterSpace(FormatterSpaceType value) {
        this.formatterSpace = value;
    }

}
